### ISSUE TITLE
Unix newlines in readme.txt and addendum.txt

### ISSUE THREAD

**Issue by gerthjaanimae** [munawarb/Treasure-Hunt#17]
A really small issue I can fix after downloading myself, but it might be a little inconvenience especially after the readme is updated. It would be much better to read in notepad this way when there is \r\n instead of \n. Or does it cause some other problems?

**Comment by munawarb** [comment]
Hi @gerthjaanimae , Thanks for pointing this out. I wasn't aware of it since I use Notepad++ to read plaintext files, and it handles Windows-style and Unix-style newlines properly.

I know what you're talking about with respect to it being garbled and difficult to read in regular Notepad. It's easy enough for me to fix, no worries!
